language: "swift"
credentials_file_path: "google.json"
categories_extension_template_path: "Templates/ios/analytics_category_template.stencil"
categories_extension_output_path: "output"
events_module_config:
  naming_postfix: "event_category"
  template_file_path: "Templates/ios/events_category_template.stencil"
  output_folder_path: "output/EventCategories"
  spreadsheet_config:
    id: "1a9UAiDPmVx_5qEv6EIpCzBx-rW64yjxH2Ptpfj6AP3A"
    page_name: "Version_1.0"
    range: "A2:G100"
user_properties_module_config:
  naming_postfix: "user_properties"
  template_file_path: "Templates/ios/user_properties_template.stencil"
  output_folder_path: "output/UserProperties"
  spreadsheet_config:
    id: "1a9UAiDPmVx_5qEv6EIpCzBx-rW64yjxH2Ptpfj6AP3A"
    page_name: "UserProps_1.0"
    range: "A2:C100"
custom_enum_module_config:
  naming_postfix: "custom_enum"
  template_file_path: "Templates/ios/custom_enums_template.stencil"
  output_folder_path: "output/CustomEnums"
  spreadsheet_config:
    id: "1a9UAiDPmVx_5qEv6EIpCzBx-rW64yjxH2Ptpfj6AP3A"
    page_name: "Types"
    range: "A2:D100"
should_remove_old_files_before_generating: true